proxy.go
proxy_test.go

this applies the patch from https://github.com/moby/moby/pull/39728;
```bash
curl -fsSL https://patch-diff.githubusercontent.com/raw/moby/moby/pull/39728.patch | git am -p3 -S
```
patch applied cleanly
-------
Currently, the escapeProxy works under the assumption that the
underlying reader will always return 1 byte at a time. Even though this
is usually true, it is not always the case, for example when using a pty
and writing multiple bytes to the master before flushing it.
In such cases the proxy reader doesn't work properly. For example with
an escape sequence being `ctrl-p,ctrl-q`, when the underlying reader
returns `ctrl-p,ctrl-q` at once, the escape sequence isn't detected.
This updates the reader to support this use-case and adds unit tests.
Signed-off-by: Bilal Amarni …

Support reading multiple bytes in escapeProxy

---

windows/ansi_reader.go
windows/ansi_writer.go
windows/console.go
windows/doc.go

follow-up to https://github.com/moby/term/pull/5 - I'll rebase once that's merged
These comments were originally in place for the moby/moby repository,
which should be imported as docker/docker. That's not an issue in this
repository, so we can remove these import comments.

remove "import" comments

---

go.mod
go.sum
term_test.go

Test no longer needs to be linux only since the pty package can handle
different platforms, and also does not require root.
This fixes an issue where the term tests are skipped in CI since there
is no TTY available.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>

Use pty for term tests

---

term_windows.go

The parts of github.com/Azure/go-ansiterm/winterm that were used
is now provided by golang.org/x/sys/windows, so switch to that
package, as it's more actively maintained.

term_windows: use golang.org/x/sys/windows

---

windows/console.go

This removes the github.com/Azure/go-ansiterm/winterm dependency from the windowsconsole package, and replaces it with `golang.org/x/sys/windows`.
Marking this function as deprecated, given that this functionality is already provided by the "standard" `golang.org/x/..` packages.

Deprecate IsConsole in favor of "golang.org/x/.." implementations

---

go.mod
go.sum

v1.1.11: Add arm support for OpenBSD
v1.1.10: Fix CTTY to work with go1.15
full diff: https://github.com/creack/pty/compare/v1.1.9...v1.1.11

go.mod: github.com/creack/pty v1.1.11

---

.github/workflows/test.yml

We were using `sudo` (without `-E`), causing environment variables that were set by `actions/setup-go` to be lost.
We need to preserve environment variables, including `PATH`, because `actions/setup-go@v2` installs Go in specific paths to allow multiple versions to be installed/cached on workers, for example, in `"/opt/hostedtoolcache/go/1.13.15/x64"`.
While it's possible to fix by adding both `-E`, and `env "PATH=$PATH"` (sudo -E does not preserve `PATH`as a security measure (see https://unix.stackexchange.com/a/83194/78656), this repository does not need `sudo` for its tests to run, so we might as well remove it altogether.
Also removing the setup-go step from the `Lint` stage, as it runs in a container, so Go is not needed on the host.
For details, see my debugging steps in …

CI: remove "sudo" to fix incorrect Go versions (incorrect PATH, GOROOT)

---

term_windows.go

Makes it possible to build with GOOS=windows and GOARCH=arm

Fix windows integer overflow

---

windows/console.go

relates to https://github.com/golang/go/issues/31044 / https://github.com/golang/crypto/commit/4be66e5b658251a93e17d931a68d9c0ecba9f83a

update godoc, as golang.org/x/crypto/ssh/terminal is deprecated

---

go.mod
go.sum

Upgraded version of Azure/go-ansiterm from `v0.0.0-20170929234023-d6e3b3328b78` to` v0.0.0-20210608035416-43c61cb656b4` which fixes issue https://github.com/moby/term/issues/26, https://github.com/kubernetes/kubernetes/issues/102404 and https://github.com/docker/for-win/issues/9770
Latest version of go-ansiterm is compatible with the stdin, stdout and stderr flags passed to `winterm.GetStdFile`  function from package `golang.org/x/sys/windows` and it's also backwards compatible with `syscall` package as well

Upgraded version of Azure/go-ansiterm

---

go.mod
go.sum

full diff: https://github.com/Azure/go-ansiterm/compare/2377c96fe7952d1240551745607860c013669458...d185dfc1b5a126116ea5a19e148e29d16b4574c9
- Go 1.15 compatibility: convert int to string using rune()
- add go.mod
- Fix int overflow

go.mod: update Azure/go-ansiterm to fix integer overflow on arm

---

term_windows.go

The code was switched back to x/sys/windows by
https://github.com/moby/term/pull/9.
/cc @thaJeztah

Remove outdated comment in func StdStreams

---

term.go

On termios platforms, interrupt signals are not generated in raw mode terminals as the ISIG setting is not enabled. Remove interrupt handler as it does nothing for raw mode and prevents other uses of INT signal with this library.
This code seems to go back all the way to moby/moby#214 where signal handling was improved for monolithic docker repository. Raw mode -ISIG got reintroduced in moby/moby@3f63b878076, but the INT handler was left behind.
Signed-off-by: Sami Loone <sloone@forcepoint.com>

term: remove interrupt handler on termios

---

windows/console.go

- relates to https://github.com/moby/term/pull/10
This function was deprecated in 57a2131dd69588daf506fde11b5c51ac6e271025 (https://github.com/moby/term/pull/10), but the comment was not formatted correctly, causing it to not be documented as deprecated on pkg.go.dev.
Also changing this back to an actual function wrapper, so that it doesn't get documented in the "Variables" section.

windows: IsConsole(): fix deprecation comment

---

windows/ansi_reader.go

Error: windows\ansi_reader.go:198:47: conversion from uint16 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
Error: windows\ansi_reader.go:201:9: conversion from uint16 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)

windows: keyToString(): fix string conversion

---

windows/ansi_reader.go
windows/ansi_reader_test.go

- fixes https://github.com/moby/term/pull/39
I must've been sleeping while writing 2ce69ef9b005eada3413f37c304c34c4bd1f2753 (https://github.com/moby/term/pull/39), because while it "fixed" the error, the intent here obviously is to return the actual character, not the number ':-)

windows: keyToString(): fix string conversion (for real)

---

term.go

- relates to https://github.com/moby/moby/pull/2954
This error was introduced in https://github.com/moby/moby/commit/aa68656cd3aefe2a64dc259e8d19c72010e4f85b (https://github.com/moby/moby/pull/2954), returned on Unix only, but was never used as a sentinel value anywhere. It doesn't appear to be used anywhere outside of this package, but let's deprecate it first before removing.

deprecate ErrInvalidState

---

.github/workflows/test.yml
term_test.go
term_unix.go

Also update some failure messages.
term_unix.go:84:27: unused-parameter: parameter 'fd' seems to be unused, consider removing or renaming it as _ (revive)
func setRawTerminalOutput(fd uintptr) (*State, error) {
^
- gha: update golangci-lint to v1.62.2 and enable default linters
- gha: update actions/setup-go@v5
- gha: update actions/checkout@v4
- gha: test against go1.22, go1.23 (latest, latest -1)

gha: update actions/setup-go@v5, actions/checkout@v4, golangci-lint to v1.62.2, test against go1.22, go1.23 (latest, latest -1)

---

.github/SECURITY.md
.github/workflows/test.yml

add concurrency check in our workflows to ensure that only a single workflow
using the same concurrency group will run at a time.
more info: https://docs.github.com/en/actions/using-jobs/using-concurrency

gha: set default permissions to "read", add concurrency check, and add security policy

---

go.mod
go.sum

relates to:
- https://github.com/Azure/go-ansiterm/issues/34
- https://github.com/Azure/go-ansiterm/pull/35
---
- fix OSC string terminator parsing
full  diff: https://github.com/Azure/go-ansiterm/compare/d185dfc1b5a1...faa5f7b0171c46bb398a91b4a0c906324d3664cf

go.mod: github.com/Azure/go-ansiterm faa5f7b0171c
